In [2]:
#Load liblary
import numpy as np

In [4]:
#Array creation , indexing and slicing
arr1 = np.array([10,20,30,40,50])
print(arr1)

[10 20 30 40 50]


In [5]:
# To 2D array
arr2 = np.array([[1,2,3],
                 [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
#Array Indexing 
print(arr1[2])

30


In [9]:
#To print 2D Indexing
print(arr2[0,1])

2


In [8]:
#Array Slicing
print(arr1[1:4])

[20 30 40]


In [10]:
# Mathmatical operations
print(arr1 + 5)

[15 25 35 45 55]


In [12]:
print(arr1 * 2)

[ 20  40  60  80 100]


In [13]:
print(np.sqrt(arr1))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [15]:
#Axis-wise opertions 
print(np.sum(arr2, axis=0)) #column wiae sum
print(np.sum(arr2, axis=1)) #Row wiae sum

[5 7 9]
[ 6 15]


In [16]:
#Statistical Operation
print(np.mean(arr1)) #Find Mean

30.0


In [17]:
print(np.median(arr1)) #Find Median

30.0


In [18]:
print(np.std(arr1)) #Find Standard deviation 


14.142135623730951


In [19]:
#To find out Max and min
print(np.max(arr1))
print(np.min(arr1))

50
10


In [22]:
#Reshaping and Brodcasting

###Reshaping
a = np.array([1,2,3,4])
b = a.reshape(2,2)
print(b)

[[1 2]
 [3 4]]


In [23]:
#Brodcasting 
c = np.array([1,2,3])
d = np.array([[1],[2],[3]])
print(c + d)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [24]:
#Save and Load Numpy Array
np.save("myarray.npy", arr1)

loaded = np.load("myarray.npy")
print(loaded)

[10 20 30 40 50]


In [26]:
#Compare performance Python list and Numpy list

### Python List
import time
list_data = list(range(1000000))
start = time.time()
result = [x * 2 for x in list_data]
print("List Time:", time.time() - start)

List Time: 0.06544232368469238


In [27]:
# NumPy array
array_data = np.arange(1000000)
start = time.time()
result = array_data * 2
print("NumPy Time:", time.time() - start)

NumPy Time: 0.017477750778198242
